### ISSUE TITLE
Unit telegram1090.service not found

### ISSUE THREAD

**Issue by PatrickS86** [flakeparadigm/telegram1090#4]
When running the service I get an error.

Unit telegram1090.service not found

What did I do wrong?

**Comment by flakeparadigm** [comment]
Hey @PatrickS86,

I'm going to need a little more information to help you troubleshoot this. Let's start with some basics-

Can you tell me...
* what OS you're running this on
* what version of that OS
* what's the exact command you are running that returns that output (copy and paste of terminal input/output between triple back-tick quotes (```) would be handy)
* what's the full file path (including full name) of the `.service` file you created
* what's the full content of the `.service` file you created
